services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourPassword123!
      - MSSQL_PID=Developer
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - public_network

  webapi:
    container_name: webapi
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=master;User=sa;Password=YourPassword123!;Encrypt=False;TrustServerCertificate=True;
    networks:
      - public_network

volumes:
  sqlserver_data:

networks:
  public_network:
    driver: bridge
