services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourPassword123! 
      - MSSQL_PID=Developer 
    volumes:
      - sqlserver_data:/var/opt/mssql 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 

volumes:
  sqlserver_data: 